project:
  type: website

website:
  title: "Darren Lin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_analysis.qmd

format:
  html:
    theme: Yeti
    css: styles.css
    toc: true

editor: visual

